[Rainmeter]
Update=1000
AccurateText=1
DynamicWindowSize=1
; 1. El AHK al principio
MouseOverAction=["H:\proyectos\Nexus_Grid_Xipi\Mini-GUI.ahk"]

@Include="#@#SteamGames.inc"

[Variables]
; 2. Las variables antes de ser usadas
ColorFondo=255,255,255,255
ColorTexto=193,141,171
EstadoJuegos=0



; 4. Las Measures que dependen de las variables o de los juegos
[MeasureIconoEstado]
Measure=Calc
Formula=#EstadoJuegos#
Substitute="0":"󱗗","1":"󱗘"
DynamicVariables=1

; 5. Ahora sí, el comando de ocultar funcionará porque el grupo "Games" ya existe
[MeasureInit]
Measure=Calc
Formula=1
OnUpdateAction=[!HideGroup "Games"]
UpdateDivider=-1

; 6. Los Meters que dibujan la interfaz
[MeterPanelControl]
Meter=String
Text="󰊴 BIBLIOTECA #TotalGames# | Modo   #VariableModo# 󰊴  #NombreJuego# [MeasureIconoEstado]" 
...
LeftMouseUpAction=[!SetVariable EstadoJuegos (1-#EstadoJuegos#)][!ToggleGroup "Games"][!UpdateMeter *][!Redraw]