[Rainmeter]
Update=-1
AccurateText=1
DynamicWindowSize=1
; Al pasar el mouse por el área del skin de Rainmeter, lanzamos el AHK
MouseOverAction=["H:\proyectos\Nexus_Grid_Xipi\Mini-GUI.ahk"]

@Include="#@#SteamGames.inc"

[Variables]
ColorFondo=255,255,255,255
ColorTexto=193,141,171

; --- ESTILO AUTOMÁTICO PARA CAPTURAR INFO ---
[EstiloJuego]
; Esta lógica lee el ToolTipText de CUALQUIER sección que use este estilo
MouseOverAction=[!SetOption MeterTextoNombre Text "[#CURRENTSECTION#:ToolTipText]"][!ShowFade "GrupoInfo"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!HideFade "GrupoInfo"][!UpdateMeter *][!Redraw]

[MeterFondoNombre]
Meter=Shape
; Redondeamos solo la esquina inferior IZQUIERDA (8). El resto rectas para unir con AHK.
Shape=Rectangle 0,0,200,34,8,8,0,0 | Fill Color #ColorFondo# | Stroke Width 0
X=((#SCREENWIDTH# / 2) - 200)
Y=0
Group=GrupoInfo
Hidden=1

[MeterTextoNombre]
Meter=String
Text=""
X=190
Y=17
FontSize=11
FontWeight=700
FontColor=#ColorTexto#
StringAlign=RightCenter
FontFace=JetBrainsMono NF
AntiAlias=1
Group=GrupoInfo
Hidden=1
DynamicVariables=1

[MeterPanelControl]
Meter=String
Text="󰊴 BIBLIOTECA [#TotalGames#] 󰅂 Ultima Revision: #UltimaFecha# | Modo Actual [#VariableModo#]" 
FontFace=JetBrainsMono NF
FontSize=13
FontColor=220,220,220
FontWeight=600
SolidColor=25,25,25,180
Padding=12,8,12,8
AntiAlias=1
X=40
Y=20
DynamicVariables=1
InlinePattern=󰊴|\[.*]\)|#TotalGames#|#VariableModo#
InlineSetting=Color | 255,170,80